name: Test
on: [push, pull_request]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
        id: go

      - uses: actions/checkout@v1

      - name: Test
        run: |
          go get -d -v
          go test -v ./...